export const config = {
  port: parseInt(process.env.PORT || '3002'),
  dbPath: process.env.DB_PATH || '/data/lens.db',
  hostProc: process.env.HOST_PROC || '/proc',
  f2bLog: process.env.F2B_LOG || '/host-var-log/fail2ban.log',
  authLog: process.env.AUTH_LOG || '/host-var-log/auth.log',
  nginxLabel: process.env.NGINX_LABEL || 'app=nginx-ingress',
  nginxNamespace: process.env.NGINX_NAMESPACE || 'nginx-ingress',
  alertWebhook: process.env.ALERT_WEBHOOK || '',
  autheliaNamespace: process.env.AUTHELIA_NAMESPACE || 'authelia',
  autheliaLabel: process.env.AUTHELIA_LABEL || 'app.kubernetes.io/component=authelia',
  crashLoopThreshold: 5,
  noLimitsThreshold: 5,
  certWarnDays: 14,
  certCritDays: 7,
  maxReplicas: 20,
  k8sApi: process.env.K8S_API || 'https://kubernetes.default.svc',
  k8sWs: process.env.K8S_WS || 'wss://kubernetes.default.svc',
  k8sTokenPath: process.env.K8S_TOKEN_PATH || '/var/run/secrets/kubernetes.io/serviceaccount/token',
  // Intervals (ms)
  systemInterval: 2000,
  podsInterval: 10000,
  healthInterval: 30000,
  attackStoreInterval: 15000,
  certCheckInterval: 300_000,
  alertHistoryMax: 200,
  tokenCacheTTL: 300_000,
  healthTimeout: 5000,
  webhookTimeout: 5000,
  nginxCacheTTL: 10000,
  cleanupInterval: 3600_000,
  // Retention
  attackRetentionDays: 30,
  apiSecret: process.env.API_SECRET || '',
}
